name: publish-on-social

on:
  push:
    branches:
      - master
#  schedule:
#    - cron: '0 4 * * *'

jobs:
  prepare-annunce:
    runs-on: ubuntu-18.04
    outputs:
      titles: ${{ toJson(fromJson(steps.read-announce-data.outputs.response).posts.*.title) }}
      urls: ${{ toJson(fromJson(steps.read-announce-data.outputs.response).posts.*.url) }}
    steps:
      - name: Read from GLV site the annunces posts and article
        uses: fjogeleit/http-request-action@master
        id: read-announce-data
        with:
            url: '${{ secrets.GLV_SITE_ANNOUNCE_DATA }}'
            method: 'GET'
      - name: Count how posts are annunced 
        id: count-post
        env:
          POSTnumber: $(echo ${{ toJson(fromJson(steps.read-announce-data.outputs.response).posts.*.title) }} | jq -c 'length')
          POSTcounter: $(echo "[ $(seq -s ", " $POSTnumber) ]")
        run: |
            POSTnumber=$(echo ${{ toJson(fromJson(steps.read-announce-data.outputs.response).posts.*.title) }} | jq -c 'length')
            POSTcounter=$(echo "[ $(seq -s ", " $POSTnumber) ]")


  publish-matrix:
    needs: prepare-annunce
    runs-on: ubuntu-18.04

    strategy:
      matrix: 
        titles: ${{fromJson(needs.prepare-annunce.outputs.titles)}}
        urls: ${{fromJson(needs.prepare-annunce.outputs.urls)}}
    steps:
    - run: |
          echo ${{matrix.titles}}
          echo ${{matrix.urls}}