name: publish-on-social

on:
  push:
    branches:
      - master
#  schedule:
#    - cron: '0 4 * * *'

jobs:
  prepare-annunce:
    runs-on: ubuntu-18.04
    outputs:
      matrix: ${{ toJson(fromJson(steps.read-announce-data.outputs.response).posts.*) }}

    steps:
      - name: Read from GLV site the annunces posts and article
        uses: fjogeleit/http-request-action@master
        id: read-announce-data
        with:
            url: '${{ secrets.GLV_SITE_ANNOUNCE_DATA }}'
            method: 'GET'

  publish-matrix:
    needs: prepare-annunce
    runs-on: ubuntu-18.04
    strategy:
      matrix: 
        titles: ${{ steps.set-titles.array }}
        urls: ${{ steps.set-urls.array }}
    steps:
    - name: Set array of titles
      id: set-titles
      run: echo "::set-output name=array::'${{ toJson(fromJson(needs.prepare-annunce.outputs.matrix).*.title) }}'"
    - name: Set array of urls
      id: set-urls
      run: echo "::set-output name=array::'${{ toJson(fromJson(needs.prepare-annunce.outputs.matrix).*.url) }}'"
