name: publish-on-social

on:
  push:
    branches:
      - master
#  schedule:
#    - cron: '0 4 * * *'

jobs:
  prepare-annunce:
    runs-on: ubuntu-18.04
    outputs:
      titles: ${{ steps.annunce-title.array }}
      urls: ${{ steps.annunce-url.array }}

    steps:
      - name: Read from GLV site the annunces posts and article
        uses: fjogeleit/http-request-action@master
        id: read-announce-data
        with:
            url: '${{ secrets.GLV_SITE_ANNOUNCE_DATA }}'
            method: 'GET'
      - name: Extract from annunce the values of attribute 'title' 
        id: annunce-list-title
        run: echo "::set-output name=list::'${{ steps.read-announce-data.outputs.response }}' | jq -c '.posts[].title'"
      - name: Extract from annunce the values of attribute 'url'
        id: annunce-list-url
        run: echo "::set-output name=list::'${{ steps.read-announce-data.outputs.response }}' | jq -c '.posts[].title'"
      - name: Convert title list into annunce-title array 
        id: annunce-title
        run: echo "::set-output name=array::'${{ steps.annunce-list-title.outputs.list }}' | jq -s "
      - name: Convert url list into annunce-url array 
        id: annunce-url
        run: echo "::set-output name=array::'${{ steps.annunce-list-url.outputs.list }}' | jq -s "

  publish-matrix:
    needs: prepare-annunce
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        titles: ${{ needs.prepare-annunce.outputs.titles }}
        urls: ${{ needs.prepare-annunce.outputs.urls }}
    steps:
    - run: echo "${{ needs.prepare-annunce.outputs.titles }}"
    - run: echo "${{ needs.prepare-annunce.outputs.urls }}"
