name: publish-on-social

on:
  push:
    branches:
      - master
#  schedule:
#    - cron: '0 4 * * *'

jobs:
  prepare-annunce:
    runs-on: ubuntu-18.04
    outputs:
      matrix: ${{ toJson(fromJson(join()) }}


    steps:
      - name: Read from GLV site the annunces posts and article
        uses: fjogeleit/http-request-action@master
        id: read-announce-data
        with:
            url: '${{ secrets.GLV_SITE_ANNOUNCE_DATA }}'
            method: 'GET'
      - name: Make matrix structure
        id: make-matrix-to-send
        env:
          TITLES: ${{ toJson(fromJson(steps.read-announce-data.outputs.response).posts.*.title) }}
          URLS: ${{ toJson(fromJson(steps.read-announce-data.outputs.response).posts.*.url) }}
          TITLE_LABEL: ${{"{\"titles\":"}}
          URL_LABEL: ${{",\"urls\":"}}
          MATRIX: ${{toJson(fromJson($(echo"$TITL_LABEL$TITLES$URL_LABEL$URLS\}")))}}

  publish-matrix:
    needs: prepare-annunce
    runs-on: ubuntu-18.04

    strategy:
      matrix: ${{fromJson(needs.prepare-annunce.outputs.matrix)}}
    steps:
    - run: echo $TITLES
    - run: echo $URLS