name: publish-on-social

on:
  push:
    branches:
      - master
#  schedule:
#    - cron: '0 4 * * *'

jobs:
  prepare-annunce:
    runs-on: ubuntu-18.04
    outputs:
      matrix: ${{ toJson(fromJson(steps.read-announce-data.outputs.response).posts) }}

    steps:
      - name: Read from GLV site the annunces posts and article
        uses: fjogeleit/http-request-action@master
        id: read-announce-data
        with:
            url: '${{ secrets.GLV_SITE_ANNOUNCE_DATA }}'
            method: 'GET'

      - run: echo "${{ toJson(fromJson(steps.read-announce-data.outputs.response).posts.*.title) }}"


  publish-matrix:
    needs: prepare-annunce
    runs-on: ubuntu-18.04

    steps:
    - run: echo "${{ toJson(fromJson(needs.prepare-annunce.outputs.matrix).*.title) }}"
    - run: echo "${{ needs.prepare-annunce.outputs.urls }}"
