name: publish-on-social

on:
  push:
    branches:
      - master
#  schedule:
#    - cron: '0 4 * * *'

jobs:
  prepare-annunce:
    runs-on: ubuntu-18.04
    outputs:
      titles: ${{ steps.annunce-title.array }}
      urls: ${{ steps.annunce-url.array }}

    steps:
      - name: Read from GLV site the annunces posts and article
        uses: fjogeleit/http-request-action@master
        id: read-announce-data
        with:
            url: '${{ secrets.GLV_SITE_ANNOUNCE_DATA }}'
            method: 'GET'
      - name: Convert from annunce the values of attribute 'title' into array 
        id: annunce-title 
        run: echo $(curl ${{ secrets.GLV_SITE_ANNOUNCE_DATA }} | jq -c '.posts | map(.title)')
      - name: Convert from annunce the values of attribute 'url' into array
        id: annunce-url
        env:
          LIST: $(echo \"${{ steps.read-announce-data.outputs.response }}\" | jq -c \".posts | map(.url)\")
        run: echo "::set-output name=array::'$LIST'"

  publish-matrix:
    needs: prepare-annunce
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        titles: ${{ needs.prepare-annunce.outputs.titles }}
        urls: ${{ needs.prepare-annunce.outputs.urls }}
    steps:
    - run: echo "${{ needs.prepare-annunce.outputs.titles }}"
    - run: echo "${{ needs.prepare-annunce.outputs.urls }}"
