name: publish-on-social

on:
  push:
    branches:
      - master
#  schedule:
#    - cron: '0 4 * * *'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: fjogeleit/http-request-action@master
      id: announce_data
      with:
          url: 'https://raw.githubusercontent.com/Getlatestversion/getlatestversion.github.io/master/announce.data'
          method: 'GET'
    - name: Convert to JSON object
      uses: gr2m/get-json-paths-action@v1.x
      id: json-convert        
      with:
        json: ${{ steps.announce_data.outputs.response }}
        publish-info: "publish-info.cut-over-date"
        posts: "posts"
    - name: Print Output
      run: |
        echo "${{ steps.json-convert.outputs.publish-info }}"

