name: publish-on-social

on:
  push:
    branches:
      - master
#  schedule:
#    - cron: '0 4 * * *'

jobs:
  prepare-annunce:
    runs-on: ubuntu-18.04
    outputs:
      matrix: ${{ steps.set-annunce.outputs.matrix }}
    steps:
      - name: Read from GLV site the annunces posts and article
        uses: fjogeleit/http-request-action@master
        id: read-announce_data
        with:
            url: '${{ secrets.GLV_SITE_ANNOUNCE_DATA }}'
            method: 'GET'
      - name: set output matrix with posts array
        id: set-annunce-matrix
        run: "::set-output name=matrix::echo '${{ steps.announce_data.outputs.response }}' | jq -c '.posts'"
  publish-matrix:
    needs: prepare-annunce
    runs-on: ubuntu-18.04
    strategy:
      matrix: fromJson(${{ needs.prepare-annunce.outputs.matrix }})
    steps:
    - run: echo "${{ needs.prepare-annunce.outputs.matrix }}"
