name: publish-on-social

on:
  push:
    branches:
      - master
#  schedule:
#    - cron: '0 4 * * *'

jobs:
  prepare-annunce:
    runs-on: ubuntu-18.04
    outputs:
      titles: ${{ fromJson(steps.read-announce-data.outputs.response.*.title) }}
      urls: ${{ fromJson(steps.read-announce-data.outputs.response.*.url) }}

    steps:
      - name: Read from GLV site the annunces posts and article
        uses: fjogeleit/http-request-action@master
        id: read-announce-data
        with:
            url: '${{ secrets.GLV_SITE_ANNOUNCE_DATA }}'
            method: 'GET'
      - run: echo ${{ fromJson(steps.read-announce-data.outputs.response.*.title) }}
      - run: echo ${{ fromJson(steps.read-announce-data.outputs.response.*.url) }}
  publish-matrix:
    needs: prepare-annunce
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        titles: ${{ needs.prepare-annunce.outputs.titles }}
        urls: ${{ needs.prepare-annunce.outputs.urls }}
    steps:
    - run: echo "${{ needs.prepare-annunce.outputs.titles }}"
    - run: echo "${{ needs.prepare-annunce.outputs.urls }}"
