name: publish-on-social

on:
  push:
    branches:
      - master
#  schedule:
#    - cron: '0 4 * * *'

jobs:
  prepare-annunce:
    runs-on: ubuntu-18.04
    outputs:
      titles: ${{ steps.annunce-title.array }}
      urls: ${{ steps.annunce-url.array }}

    steps:
      - name: Read from GLV site the annunces posts and article
        uses: fjogeleit/http-request-action@master
        id: read-announce-data
        with:
            url: '${{ secrets.GLV_SITE_ANNOUNCE_DATA }}'
            method: 'GET'
      - name: Traslate annunce attribute 'title' into array
        id: annunce-title
        run: "echo '$(echo \'${{ steps.read-announce-data.outputs.response }}\' | jq -c \'.posts[].title\')'| jq -s"
      - name: Traslate annunce attribute 'url' into array
        id: annunce-url
        run: "echo '$("echo \'${{ steps.read-announce-data.outputs.response }}\' | jq -c \'.posts[].url\')' | js -s"

  publish-matrix:
    needs: prepare-annunce
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        titles: ${{ needs.prepare-annunce.outputs.titles }}
        urls: ${{ needs.prepare-annunce.outputs.urls }}
    steps:
    - run: echo "${{ needs.prepare-annunce.outputs.titles }}"
    - run: echo "${{ needs.prepare-annunce.outputs.urls }}"
