name: publish-on-social

on:
  push:
    branches:
      - master
#  schedule:
#    - cron: '0 4 * * *'

jobs:
  prepare-annunce:
    runs-on: ubuntu-18.04
    outputs:
      titles: ${{ toJson(fromJson(steps.read-announce-data.outputs.response).posts.*.title) }}
      urls: ${{ toJson(fromJson(steps.read-announce-data.outputs.response).posts.*.url) }}
      counter: ${{ steps.count-post.outputs.counter }}
    steps:
      - name: Read from GLV site the annunces posts and article
        uses: fjogeleit/http-request-action@master
        id: read-announce-data
        with:
            url: '${{ secrets.GLV_SITE_ANNOUNCE_DATA }}'
            method: 'GET'
      - name: Count how posts are annunced 
        id: count-post
        run: |
            POSTnumber=$(echo '${{ toJson(fromJson(steps.read-announce-data.outputs.response).posts.*.title) }}' | jq -c 'length')
            POSTnumber=$(($POSTnumber - 1))
            POSTcounter=$(echo "[ $(seq -s ", " 0 $POSTnumber) ]")
            echo $POSTnumber
            echo "::set-output name=counter::$POSTcounter"


  publish-matrix:
    needs: prepare-annunce
    runs-on: ubuntu-18.04

    strategy:
      matrix: 
        counter: ${{fromJson(needs.prepare-annunce.outputs.counter)}}

    steps:
    - run: |
          echo ${{fromJson(needs.prepare-annunce.outputs.titles)[matrix.counter]}}
          echo ${{fromJson(needs.prepare-annunce.outputs.urls)[matrix.counter]}}