name: publish-on-social

on:
  push:
    branches:
      - master
#  schedule:
#    - cron: '0 4 * * *'

jobs:
  prepare-annunce:
    runs-on: ubuntu-18.04
    outputs:
      matrix: ${{ steps.traslate-object-2-array.outputs.matrix }}
    steps:
      - name: Read from GLV site the annunces posts and article
        uses: fjogeleit/http-request-action@master
        id: read-announce-data
        with:
            url: '${{ secrets.GLV_SITE_ANNOUNCE_DATA }}'
            method: 'GET'
      - name: Traslate annunce objects into attributes array
        id: traslate-object-2-array
        run: "echo '${{ steps.read-announce-data.outputs.response }}'|jq -c '.posts[].title'| jq -s ; echo '${{ steps.read-announce-data.outputs.response }}'|jq -c '.posts[].url'| jq -s"

  publish-matrix:
    needs: prepare-annunce
    runs-on: ubuntu-18.04
    strategy:
      matrix: ${{ needs.prepare-annunce.outputs.matrix }}
    steps:
    - run: echo "${{ needs.prepare-annunce.outputs.matrix }}"
