name: publish-on-social

on:
  push:
    branches:
      - master
#  schedule:
#    - cron: '0 4 * * *'

jobs:
  prepare-annunce:
    runs-on: ubuntu-18.04
    outputs:
      matrix.titles: ${{toJson(fromJson(${{steps.read-announce-data.outputs.response}}).posts[].title)}}
      matrix.urls: ${{toJson(fromJson(${{steps.read-announce-data.outputs.response}}).posts[].url)}}

    steps:
      - name: Read from GLV site the annunces posts and article
        uses: fjogeleit/http-request-action@master
        id: read-announce-data
        with:
            url: '${{ secrets.GLV_SITE_ANNOUNCE_DATA }}'
            method: 'GET'

  publish-matrix:
    needs: prepare-annunce
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        titles: ${{ needs.prepare-annunce.outputs.matrix.titles }}
        urls: ${{ needs.prepare-annunce.outputs.matrix.urls }}
    steps:
    - run: echo "${{ needs.prepare-annunce.outputs.matrix }}"
