name: publish-on-social

on:
  push:
    branches:
      - master
#  schedule:
#    - cron: '0 4 * * *'

jobs:
  prepare-annunce:
    runs-on: ubuntu-18.04
    outputs:
      titles: ${{ steps.read-announce-data.outputs.response.*.title }}
      urls: ${{ steps.read-announce-data.outputs.response.*.url }}

    steps:
      - name: Read from GLV site the annunces posts and article
        uses: fjogeleit/http-request-action@master
        id: read-announce-data
        with:
            url: '${{ secrets.GLV_SITE_ANNOUNCE_DATA }}'
            method: 'GET'
            
  publish-matrix:
    needs: prepare-annunce
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        titles: ${{ fromJson(needs.prepare-annunce.outputs.titles) }}
        urls: ${{ fromJson(needs.prepare-annunce.outputs.urls) }}
    steps:
    - run: echo "${{ needs.prepare-annunce.outputs.titles }}"
    - run: echo "${{ needs.prepare-annunce.outputs.urls }}"
